version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./db_inits:/docker-entrypoint-initdb.d/:ro
      - ${DB_PATH}:/var/lib/mysql
    env_file:
      - .env
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  web_app:
    depends_on:
      - db
      - redis
    container_name: home_music_web_app
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${FILES_PATH}:/HomeMusic/files
    env_file:
      - .env
