version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - ./db_inits:/docker-entrypoint-initdb.d/:ro
      - ${DB_PATH}:/var/lib/mysql
    env_file:
      - .env
