version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  web_app:
    depends_on:
      - redis
    container_name: home_music_web_app
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${FILES_PATH}:/HomeMusic/files
      - ${DB_PATH}:/HomeMusic/database
    env_file:
      - .env
